' SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
'
' SPDX-License-Identifier: Apache-2.0

@startuml

!theme spacelab
skinparam ArrowFontColor #000000

(*) -->[Extractcode] "Source Code"
"Source Code" -->[via opossum.lib.hs] "Opossum Input\nfrom Filetree"


partition "OSS Review Toolkit\n(fork)" #eeeeee {
    "Source Code" -->[ORT analyze] "Analyzer Result"
    "Analyzer Result" -->[ORT scan] "Scanner Result"
    "Analyzer Result" ...>[ORT report] "Opossum Input\nfrom ORT"
    "Scanner Result" -->[ORT report] "Opossum Input\nfrom ORT"
}

partition ScanCode #eeeeee {
    "Source Code" -->[ScanCode Scan] "ScanCode Result"
}

partition "OWASP\nDependency-Check" #eeeeee {
    "Source Code" --->[Dependency-Check] "Dependency-Check Result"
}

partition SCANOSS #eeeeee {
    "Source Code" --->[SCANOSS Scan] "SCANOSS Result"
    partition convertSCA.sh #dddddd {
        "Opossum Input\nfrom Filetree" --> "Opossum Input\nfrom SCANOSS"
        "SCANOSS Result" -->[Convert] "Opossum Input\nfrom SCANOSS"
    }
}

partition opossum.lib.hs #eeeeee {
    ' "ScanCode Result" ..> "Opossum Input\nfrom ScanCode"
    ' "Opossum Input\nfrom ScanCode" ..> "Merged\nOpossum Input"
    "Opossum Input\nfrom ORT" --> "Merged\nOpossum Input"
    "ScanCode Result" ---> "Merged\nOpossum Input"
    "Opossum Input\nfrom SCANOSS" --> "Merged\nOpossum Input"
    "Dependency-Check Result" --> "Merged\nOpossum Input"
}

"Merged\nOpossum Input" -->[gzip] (*)

@enduml